### ISSUE TITLE
App stop working

### ISSUE THREAD

**Issue by ch-rigu** [valq7711/vue3pyj#4]
I'v just cloned the app with a updated py4web and i'm getting this error.

`Traceback (most recent call last):
  File "/home/chris/develop/py4web/py4web/core.py", line 945, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/chris/develop/py4web/py4web/core.py", line 930, in wrapper
    raise context["exception"]
  File "/home/chris/develop/py4web/py4web/core.py", line 907, in wrapper
    call(fixture.on_request, context)
  File "/home/chris/develop/py4web/py4web/core.py", line 892, in call
    return f(context)
TypeError: on_request() takes 1 positional argument but 2 were given
 > Thread-3 > 20:09:09.940
[2023-11-28T20:09:10.015646]: Traceback (most recent call last):
  File "/home/chris/develop/py4web/py4web/core.py", line 945, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/chris/develop/py4web/py4web/core.py", line 930, in wrapper
    raise context["exception"]
  File "/home/chris/develop/py4web/py4web/core.py", line 907, in wrapper
    call(fixture.on_request, context)
  File "/home/chris/develop/py4web/py4web/core.py", line 892, in call
    return f(context)
TypeError: on_request() takes 1 positional argument but 2 were given

Traceback (most recent call last):
  File "/home/chris/develop/py4web/py4web/core.py", line 945, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/chris/develop/py4web/py4web/core.py", line 930, in wrapper
    raise context["exception"]
  File "/home/chris/develop/py4web/py4web/core.py", line 907, in wrapper
    call(fixture.on_request, context)
  File "/home/chris/develop/py4web/py4web/core.py", line 892, in call
    return f(context)
TypeError: on_request() takes 1 positional argument but 2 were given
 > Thread-3 > 20:09:10.018`

I really would like to use this app since is more simple and easy to use than _dashboard itself. I've tried time a go and is was working great.

**Comment by ch-rigu** [comment]
I've re entered admin password (I was already loged in in _dashboard app) and start working again !
